In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('https://opendata.ecdc.europa.eu/covid19/casedistribution/csv')

In [5]:
df

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018,continentExp
0,09/06/2020,9,6,2020,575,12,Afghanistan,AF,AFG,37172386.0,Asia
1,08/06/2020,8,6,2020,791,30,Afghanistan,AF,AFG,37172386.0,Asia
2,07/06/2020,7,6,2020,582,18,Afghanistan,AF,AFG,37172386.0,Asia
3,06/06/2020,6,6,2020,915,9,Afghanistan,AF,AFG,37172386.0,Asia
4,05/06/2020,5,6,2020,787,6,Afghanistan,AF,AFG,37172386.0,Asia
...,...,...,...,...,...,...,...,...,...,...,...
22378,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0,Africa
22379,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0,Africa
22380,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0,Africa
22381,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0,Africa
22382,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0,Africa

In [6]:
df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018,continentExp
0,09/06/2020,9,6,2020,575,12,Afghanistan,AF,AFG,37172386.0,Asia
1,08/06/2020,8,6,2020,791,30,Afghanistan,AF,AFG,37172386.0,Asia
2,07/06/2020,7,6,2020,582,18,Afghanistan,AF,AFG,37172386.0,Asia
3,06/06/2020,6,6,2020,915,9,Afghanistan,AF,AFG,37172386.0,Asia
4,05/06/2020,5,6,2020,787,6,Afghanistan,AF,AFG,37172386.0,Asia